title: Learnin how to blog
author: Michael
email: mgfenn157@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A simple learning experience about setting up a blog on github

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Michael-Fenn

show_excerpts: true # set to false to remove excerpts on the homepage
